language: objective-c
osx_image: xcode7.3
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xctool -workspace ACServiceProvider.xcworkspace -scheme ACServiceProvider -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace ACServiceProvider.xcworkspace -scheme ACServiceProviderTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
