before_install:
  - gem install cocoapods -v '0.39'
osx_image: xcode7.3
rvm: 2.2.2
language: swift
xcode_project: ACServiceProvider.xcodeproj
xcode_scheme: ACServiceProviderTests
xcode_sdk: iphonesimulator9.2
script:
  - xctool -workspace ACServiceProvider.xcworkspace -scheme ACServiceProvider -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace ACServiceProvider.xcworkspace -scheme ACServiceProviderTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
