language: objective-c
osx_image: xcode7.2
xcode_workspace: ACServiceProvider.xcworkspace
xcode_scheme: ACServiceProvider
xcode_sdk: iphonesimulator9.2
env:
  global: 
    - FRAMEWORK_NAME=ACServiceProvider
before_install:
  - brew update
  - brew install carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
