language: objective-c
osx_image: xcode7.2
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace ACServiceProvider.xcworkspace -scheme ACServiceProvider -sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace ACServiceProvider.xcworkspace -scheme ACServiceProviderTests -sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=NO
