before_install:
  - gem install cocoapods -v '0.39'
rvm: 2.2.2
language: swift
osx_image: xcode7.3
xcode_project: ACServiceProvider.xcodeproj
xcode_scheme: ACServiceProvider
xcode_sdk: iphonesimulator9.2
